app/urls.py
from django.urls import path
from . import views


app_name = 'app'
urlpatterns = [
    path('',views.home, name='home'),
    path('message/',views.message, name='message'),
    path('gallary2/',views.gallary2, name='gallary2'),
    path('gallary/',views.gallary, name='gallary'),
    path('more/',views.pastor_more, name='more'),
    path('videos/',views.videos, name='video'),
    path('audio/',views.audios_video, name='audio'),
    path('audios/',views.audios, name='audio'),
    path('events/',views.events, name='events'),
    path('pastors_unit/',views.pastors_unit, name='pastors_unit'),
    path('contact/',views.contact_us, name='contact_us'),

    #UNITS
    path('choir/',views.choir, name='choir'),
    path('usher/',views.ushers, name='ushers'),
    path('media/',views.media, name='media'),
    path('decoration/',views.decoration, name='decoration'),
    path('sanitation/',views.sanitation, name='sanitation'),
    path('protocol/',views.protocol, name='protocol'),
    path('security_unit/',views.security, name='security'),
    path('sunday_school/',views.sunday, name='sunday_school'),
    path('technical/',views.technical, name='technical'),





    path('<slug>/',views.details, name='detail'),



]

mercy/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings 


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('app.urls')),
    path('control/',include('control_panel.urls')),
    path('news/',include('newsletter.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

newsletter/urls.py
from django.urls import path
from . import views

app_name = 'newsletter'

urlpatterns = [
	path('sign_up/', views.newsletter_signup, name="sign_up"),
	path('unsubscribe',views.newsletter_unsubscribe, name="unsubscribe"),
]

newsletter/models.py
from django.db import models

# Create your models here.

class NewsletterUser(models.Model):
	email = models.EmailField()
	date_added = models.DateTimeField(auto_now_add=True)

	def __str__(self):
		return self.email

class Newsletter(models.Model):
	EMAIL_STATUS_CHOICE = (
			('Draft','Draft'),
			('Published', 'Published')
		)
	subject = models.CharField(max_length=250)
	body = models.TextField()
	email = models.ManyToManyField(NewsletterUser)
	status = models.CharField(max_length=10, choices=EMAIL_STATUS_CHOICE)
	created = models.DateTimeField(auto_now_add=True)
	updated = models.DateTimeField(auto_now=True)

	def __str__(self):
		return self.subject

newsletter/forms.py
from django import forms

from .models import NewsletterUser, Newsletter

class NewsletterUserSignUpForm(forms.ModelForm):
	class Meta:
		model = NewsletterUser
		fields = ['email']

		widgets = {
				'email': forms.TextInput(attrs={ 'class':'form-control'}),
			
		}

		def clean_email(self):
			email = self.cleaned_data.get('email')

			return email

class NewsletterCreationForm(forms.ModelForm):

	class Meta:
		model = Newsletter
		fields = ['subject', 'body', 'email', 'status']

		widgets = {
				'subject': forms.TextInput(attrs={ 'class':'form-control'}),
				'body': forms.Textarea(attrs={ 'class':'form-control'}),
				'email': forms.SelectMultiple(attrs={ 'class':'form-control related-widget-wrapper','required id':'id_email','name':'email'}),
				'status': forms.Select(attrs={ 'class':'form-control'}),
			
		}


		

newsletter/views.py
from django.conf import settings
from django.contrib import messages
from django.shortcuts import render
from django.core.mail import send_mail, EmailMultiAlternatives
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.template.loader import get_template

from .models import NewsletterUser, Newsletter
from .forms import NewsletterUserSignUpForm, NewsletterCreationForm

def newsletter_signup(request):
	form = NewsletterUserSignUpForm(request.POST or None)

	if form.is_valid():
		instance = form.save(commit=False)
		if NewsletterUser.objects.filter(email=instance.email).exists():
			messages.warning(request,'your email already exists in our database', "alert alert-warning alert-dismissible")
		else:
			instance.save()
			messages.success(request, 'Your email has been submitted to the database', "alert alert-success alert-dismissible")
			subject = "Thank you for Joining Our NewsLetter"
			from_email = settings.EMAIL_HOST_USER
			to_email = [instance.email]
			with open(settings.BASE_DIR + "/newsletter/templates/newsletter/sign_up_email.txt") as f:
				signup_message = f.read()
			message = EmailMultiAlternatives(subject=subject, body=signup_message, from_email=from_email, to=to_email)
			html_template = get_template("newsletter/sign_up_email.html").render()
			message.attach_alternative(html_template, "text/html")
			message.send()

	context = {
		"form": form,
	}
	# template = "newsletter/sign_up.html"
	return render(request,"newsletter/sign_up.html" , context)

def newsletter_unsubscribe(request):
	form = NewsletterUserSignUpForm(request.POST or None)

	if form.is_valid():
		instance = form.save(commit=False)
		if NewsletterUser.objects.filter(email=instance.email).exists():
			NewsletterUser.objects.filter(email=instance.email).delete()
			messages.success(request, 'You have Being unsubscribe', 'alert alert-success alert-dismissible')

			subject = "You have being Unsubscribe"
			from_email = settings.EMAIL_HOST_USER
			to_email = [instance.email]
			with open(settings.BASE_DIR + "/newsletter/templates/newsletter/unsubscribe_email.txt") as f:
				signup_message = f.read()
			message = EmailMultiAlternatives(subject=subject, body=signup_message, from_email=from_email, to=to_email)
			html_template = get_template("newsletter/unsubscribe_email.html").render()
			message.attach_alternative(html_template, "text/html")
			message.send()
		else:
			messages.warning(request,'your email is not in the database', "alert alert-warning alert-dismissible")
	context = {
		"form": form,
	}

	template = "newsletter/unsubscribe.html"
	return render(request, template, context)

def control_newsletter(request):
	form = NewsletterCreationForm(request.POST or None)

	if form.is_valid():
		instance = form.save()
		newsletter = Newsletter.objects.get(id=instance.id)
		if newsletter.status == "Published":
			subject = newsletter.subject
			body = newsletter.body
			from_email =settings.EMAIL_HOST_USER
			for email in newsletter.email.all():
				send_mail(subject=subject, from_email=from_email, recipient_list=[ email ], message=body, fail_silently=True)

	context = {
		"form":form,
	}
	template = "control_panel/control_newsletter.html"
	return render(request, template, context)

def control_newsletter_list(request):
	newsletter = Newsletter.objects.all()

	paginator = Paginator(newsletter, 10)
	page = request.GET.get('page')

	try:
		items = paginator.page(page)
	except PageNotAnInteger:
		items = paginator.page(1)
	except EmptyPage:
		items = paginator.page(paginator.num_pages)

	index = items.number -1
	max_index = len(paginator.page_range)
	start_index = index -5 if index >= 5 else 0
	end_index = index + 5 if index <= max_index -5 else max_index
	page_range = paginator.page_range[start_index:end_index]

	context= {
		"items":items,
		"page_range":page_range
	}
	template = "control_panel/control_newsletter_list.html"
	return render(request, template, context)

newsletter/templates/newsletter/alert.html
<!-- <div class="col-lg-6 col-md-6 footer-newsletter">
	            <center><h3>Our Newsletter</h3></center>
	  			{% if messages %}
	  				{% for message in massages %}
	  				<div % if message.tags %} class="{% message.tags %}" {% endif %} role="alert">
	  					<button type="button" class="close" data-dismiss="alert"aria-label=Close><span aria-hidden="true">&times;</span></button>
	  					{{ message }}
	  				</div>
	  				{% endfor %}
	  			{% else %}
	            <form action="" method="POST">{% csrf_token %}
	              {{ form }}<center><input class="btn btn-default mt-2 mb-2" type="submit" value="Subscribe"></center>
	              
	            </form>
	            {% endif %}
	    </div> -->



	    <!-- subject = "Thank you for Joining Our NewsLetter"
			from_email = settings.EMAIL_HOST_USER
			to_email = [instance.email]
			with open(settings.BASE_DIR + "/newsletter/templates/newsletter/sign_up_email.txt") as f:
				signup_message = f.read()
			message = EmailMultiAlternatives(subject=subject, body=signup_message, from_email=from_email, to=to_email)
			html_template = get_template("newsletter/sign_up_email.html").render()
			message.attach_alternative(html_template, "text/html")
			message.send() -->

newsletter/templates/newsletter/sign_up.html
{% extends 'inc/base.html' %}
{% load static %}
{% block content %}
	<!-- <div class="container">
		<div class="row">
			<div class="col-lg-6 col-lg-offset-3">
				<h3 class="text-center">Sign Up NewsLetter</h3>
				<form method="POST">{% csrf_token %}
					<div class="input-group">
						{{ form }}
						<span class="input-group-btn">
							<button class="btn btn-default">Subscribe</button>
						</span>
					</div>	
				</form>
			</div>
		</div>
	</div> -->
<div class="container">
	<div class="row mt-3">
		<div class="col-lg-3 col-md-6 footer-newsletter">
	            
	    </div>
	 <div class="col-lg-6 col-md-6 footer-newsletter">
	            <center><h3>Sign Up For Our Newsletter</h3></center>
	  			{% if messages %}
	  				{% for message in messages %}
	  				<div {% if message.tags %} class="{{ message.tags }}" {% endif %} role="alert">
	  					<button type="button" class="close" data-dismiss="alert"aria-label=Close><span aria-hidden="true">&times;</span></button>
	  					{{ message }}
	  				</div>
	  				{% endfor %}
	  			{% else %}
	            <form action="" method="POST">{% csrf_token %}
	              {{ form }}<center><input class="btn btn-default mt-2 mb-2" type="submit" value="Subscribe"></center>
	              
	            </form>
	            {% endif %}
	    </div> 
	    <div class="col-lg-3 col-md-6 footer-newsletter">
	            
	    </div>
	</div>
</div>
{% endblock %}

newsletter/templates/newsletter/sign_up_email.html
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>
	<h2>Welcome to house of Mercy NewsLetter</h2>
	<p>Thank you for joining</p>
	<p>To unsubscribe visit this link: <a href="{% url 'newsletter:unsubscribe' %}">Unsubscribe</a></p>
</body>
</html>

newsletter/templates/newsletter/unsubscribe.html
{% extends 'inc/base.html' %}
{% load static %}
{% block content %}
	<!-- <div class="container">
		<div class="row">
			<div class="col-lg-6 col-lg-offset-3">
				<h3 class="text-center">Sign Up NewsLetter</h3>
				<form method="POST">{% csrf_token %}
					<div class="input-group">
						{{ form }}
						<span class="input-group-btn">
							<button class="btn btn-default">Subscribe</button>
						</span>
					</div>	
				</form>
			</div>
		</div>
	</div> -->
<div class="container">
	<div class="row mt-3">
		<div class="col-lg-3 col-md-6 footer-newsletter">
	            
	    </div>
	 <div class="col-lg-6 col-md-6 footer-newsletter">
	            <center><h3>Unsubscribe From Our Newsletter</h3></center>
	  			{% if messages %}
	  				{% for message in messages %}
	  				<div {% if message.tags %} class="{{ message.tags }}" {% endif %} role="alert">
	  					<button type="button" class="close" data-dismiss="alert"aria-label=Close><span aria-hidden="true">&times;</span></button>
	  					{{ message }}
	  				</div>
	  				{% endfor %}
	  			{% else %}
	            <form action="" method="POST">{% csrf_token %}
	              {{ form }}<center><input class="btn btn-default mt-2 mb-2" type="submit" value="Unsubscribe"></center>
	              
	            </form>
	            {% endif %}
	    </div> 
	    <div class="col-lg-3 col-md-6 footer-newsletter">
	            
	    </div>
	</div>
</div>
{% endblock %}

newsletter/templates/newsletter/unsubscribe_email.html
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>
	<h2>Sorry to see you go</h2>
	<p>Bye Bye</p>
</body>
</html>