app/urls.py
from django.urls import path
from . import views


app_name = 'app'
urlpatterns = [
    path('',views.home, name='home'),
    path('message/',views.message, name='message'),
    path('gallary2/',views.gallary2, name='gallary2'),
    path('gallary/',views.gallary, name='gallary'),
    path('more/',views.pastor_more, name='more'),
    path('videos/',views.videos, name='video'),
    path('audio/',views.audios_video, name='audio'),
    path('audios/',views.audios, name='audio'),
    path('events/',views.events, name='events'),
    path('pastors_unit/',views.pastors_unit, name='pastors_unit'),
    path('contact/',views.contact_us, name='contact_us'),

    #UNITS
    path('choir/',views.choir, name='choir'),
    path('usher/',views.ushers, name='ushers'),
    path('media/',views.media, name='media'),
    path('decoration/',views.decoration, name='decoration'),
    path('sanitation/',views.sanitation, name='sanitation'),
    path('protocol/',views.protocol, name='protocol'),
    path('security_unit/',views.security, name='security'),
    path('sunday_school/',views.sunday, name='sunday_school'),
    path('technical/',views.technical, name='technical'),





    path('<slug>/',views.details, name='detail'),



]

mercy/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings 


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('app.urls')),
    path('control/',include('control_panel.urls')),
    path('news/',include('newsletter.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/templates/inc/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>RCCGHOM</title>
  <meta content="" name="descriptison">
  <meta content="" name="keywords">

  <!-- Favicons -->
  <link href="{% static 'assets/img/favicon.png' %}" rel="icon">
  <link href="{% static 'assets/img/apple-touch-icon.png' %}" rel="apple-touch-icon">

  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Roboto:300,300i,400,400i,500,500i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="{% static 'assets/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/icofont/icofont.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/boxicons/css/boxicons.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/animate.css/animate.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/owl.carousel/assets/owl.carousel.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/venobox/venobox.css' %}" rel="stylesheet">

  <!-- Template Main CSS File -->
  <link href="{% static 'assets/css/style.css' %}" rel="stylesheet">
  <link href="{% static 'assets/css/lightbox.css' %}" rel="stylesheet">

</head>
<body>


<header id="header">
  <div class="container d-flex">

          <div class="logo mr-auto">
            <h1 class="text-light" ><a href="{% url 'app:home' %}" alt="" class="img-fluid"><img src="{% static 'assets/img/logo.png' %}"> <span>HOUSE OF MERCY</span></a></h1>
            <!-- Uncomment below if you prefer to use an image logo -->
            <!-- <a href="index.html"><img src="assets/img/logo.png" alt="" class="img-fluid"></a>-->
          </div>

        <nav class="nav-menu d-none d-lg-block">
            <ul>
              <li class="active"><a href="{% url 'app:home' %}">Home</a></li>          
              <li class="drop-down"><a href="">Units</a>
                <ul>
                  <li><a href="{% url 'app:pastors_unit' %}">Pastorate Unit</a></li>
                  <li><a href="{% url 'app:choir' %}">Choir Unit</a></li> 
                  <li><a href="{% url 'app:ushers' %}">Usering Unit</a></li> 
                  <li><a href="{% url 'app:media' %}">Media Unit</a></li> 
                  <li><a href="{% url 'app:decoration' %}">Decoration Unit</a></li> 
                  <li><a href="{% url 'app:sanitation' %}">Sanitation Unit</a></li> 
                  <li><a href="{% url 'app:protocol' %}">Protocol Unit</a></li> 
                  <li><a href="{% url 'app:security' %}">Security Unit</a></li> 
                  <li><a href="{% url 'app:sunday_school' %}">Sunday School Unit</a></li> 
                  <li><a href="{% url 'app:technical' %}">Technical Unit</a></li> 
                </ul>
              </li>
              <li class="drop-down"><a href="">Media</a>
                <ul>
                  <li><a href="{% url 'app:video' %}">Videos</a></li>
                  <li><a href="{% url 'app:audio' %}">Audios</a></li> 
                </ul>
              </li>
              <li><a href="{% url 'app:more' %}">Pastor's Desk</a></li>          

              <li><a href="{% url 'app:contact_us' %}">Contact Us</a></li>
              <li><a href="{% url 'app:gallary' %}">Gallary</a></li>
              <li><a href="{% url 'app:events' %}">Events</a></li>

            </ul>

        </nav><!-- .nav-menu -->
  </div>
</header>
{% block content %}
  
{% endblock content %}
<footer id="footer">
    <div class="footer-top">
      <div class="container">
        <div class="row">

          <div class="col-lg-4 col-md-6 footer-info">
            <h3>RCCG House Of Mercy Bauchi</h3>
            <p>
              Opposit New Trafford Beside Federal Poly ,Bauchi  <br>
              <br><br>
              <strong>Phone:</strong> +1 5589 55488 55<br>
              <strong>Email:</strong> info@example.com<br>
            </p>
            <div class="social-links mt-3">
              <a href="#" class="twitter"><i class="bx bxl-twitter"></i></a>
              <a href="#" class="facebook"><i class="bx bxl-facebook"></i></a>
              <a href="#" class="instagram"><i class="bx bxl-instagram"></i></a>
              <a href="#" class="google-plus"><i class="bx bxl-skype"></i></a>
              <a href="#" class="linkedin"><i class="bx bxl-linkedin"></i></a>
            </div>
          </div>

          <div class="col-lg-4 col-md-6 footer-links">
           <center> <h4> Weekly Activities</h4></center>
            <ul>
              <li><i class="bx bx-chevron-right"></i>Tuesday: Digging Deep 5:00pm -- 6:00pm</li>
              <li><i class="bx bx-chevron-right"></i>Thurday: Faith Clinic 5:00pm -- 6:00pm</li>
              <li><i class="bx bx-chevron-right"></i>Sunday:First Service 7:30am </li>
              <li><i class="bx bx-chevron-right"></i>Sunday:Second Service 9:15am</li>
              <li><i class="bx bx-chevron-right"></i>Wenesday: Solution Hour 6:00am -- 7:00am</li>
              <li><i class="bx bx-chevron-right"></i>Saturday: Prayer 7:00am -- 8:00am</li>
            </ul>
          </div>

          <div class="col-lg-4 col-md-6 footer-links">
            <h4>Useful Links</h4>
            <ul>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Home</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Units</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Media</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Pastors Desk</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Contact Us</a></li>
            </ul>
          </div>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="copyright">
        &copy; Copyright <strong><span>House Of Mercy</span></strong>. All Rights Reserved
      </div>
      <div class="credits">
        <!-- All the links in the footer should remain intact. -->
        <!-- You can delete the links only if you purchased the pro version. -->
        <!-- Licensing information: https://bootstrapmade.com/license/ -->
        <!-- Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/bootstrap-3-one-page-template-free-shuffle/ -->
        Designed by <a href="">House Of Mercy Media Team</a>
      </div>
    </div>
  </footer>
  <script src="{% static 'assets/vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'assets/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'assets/vendor/jquery.easing/jquery.easing.min.js' %}"></script>
  <script src="{% static 'assets/vendor/php-email-form/validate.js' %}"></script>
  <script src="{% static 'assets/vendor/jquery-sticky/jquery.sticky.js' %}"></script>
  <script src="{% static 'assets/vendor/waypoints/jquery.waypoints.min.js' %}"></script>
  <script src="{% static 'assets/vendor/counterup/counterup.min.js' %}"></script>
  <script src="{% static 'assets/vendor/isotope-layout/isotope.pkgd.min.js' %}"></script>
  <script src="{% static 'assets/vendor/owl.carousel/owl.carousel.min.js' %}"></script>
  <script src="{% static 'assets/vendor/venobox/venobox.min.js' %}"></script>

  <!-- Template Main JS File -->
  <script src="{% static 'assets/js/main.js' %}"></script>
  <script src="{% static 'assets/js/lightbox.min.js' %}"></script>
</body>
</html>

app/templates/inc/control_base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>RCCGHOM</title>
  <meta content="" name="descriptison">
  <meta content="" name="keywords">

  <!-- Favicons -->
  <link href="{% static 'assets/img/favicon.png' %}" rel="icon">
  <link href="{% static 'assets/img/apple-touch-icon.png' %}" rel="apple-touch-icon">

  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Roboto:300,300i,400,400i,500,500i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="{% static 'assets/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/icofont/icofont.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/boxicons/css/boxicons.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/animate.css/animate.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/owl.carousel/assets/owl.carousel.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/venobox/venobox.css' %}" rel="stylesheet">

  <!-- Template Main CSS File -->
  <link href="{% static 'assets/css/style.css' %}" rel="stylesheet">
  <link href="{% static 'assets/css/lightbox.css' %}" rel="stylesheet">

</head>
<body>


<header id="header">
  <div class="container d-flex">

          <div class="logo mr-auto">
            <h1 class="text-light" ><a href="{% url 'app:home' %}" alt="" class="img-fluid"><img src="{% static 'assets/img/logo.png' %}"> <span>HOUSE OF MERCY</span></a></h1>
            <!-- Uncomment below if you prefer to use an image logo -->
            <!-- <a href="index.html"><img src="assets/img/logo.png" alt="" class="img-fluid"></a>-->
          </div>

        <nav class="nav-menu d-none d-lg-block">
            <ul>
              <li class="active"><a href="{% url 'app:home' %}">Home</a></li>          
              <li class="drop-down"><a href="">Units</a>
                <ul>
                  <li><a href="{% url 'app:pastors_unit' %}">Pastorate Unit</a></li>
                  <li><a href="{% url 'app:choir' %}">Choir Unit</a></li> 
                  <li><a href="{% url 'app:ushers' %}">Usering Unit</a></li> 
                  <li><a href="{% url 'app:media' %}">Media Unit</a></li> 
                  <li><a href="{% url 'app:decoration' %}">Decoration Unit</a></li> 
                  <li><a href="{% url 'app:sanitation' %}">Sanitation Unit</a></li> 
                  <li><a href="{% url 'app:protocol' %}">Protocol Unit</a></li> 
                  <li><a href="{% url 'app:security' %}">Security Unit</a></li> 
                  <li><a href="{% url 'app:sunday_school' %}">Sunday School Unit</a></li> 
                  <li><a href="{% url 'app:technical' %}">Technical Unit</a></li> 
                </ul>
              </li>
              <li class="drop-down"><a href="">Media</a>
                <ul>
                  <li><a href="{% url 'app:video' %}">Videos</a></li>
                  <li><a href="{% url 'app:audio' %}">Audios</a></li> 
                </ul>
              </li>
              <li><a href="{% url 'app:more' %}">Pastor's Desk</a></li>          

              <li><a href="{% url 'app:contact_us' %}">Contact Us</a></li>
              <li><a href="{% url 'app:gallary' %}">Gallary</a></li>
              <li><a href="{% url 'app:events' %}">Events</a></li>

            </ul>

        </nav><!-- .nav-menu -->
  </div>
</header>
{% block content %}
  
{% endblock content %}
<footer id="footer">
    <div class="footer-top">
      <div class="container">
        <div class="row">

          <div class="col-lg-4 col-md-6 footer-info">
            <h3>RCCG House Of Mercy Bauchi</h3>
            <p>
              Opposit New Trafford Beside Federal Poly ,Bauchi  <br>
              <br><br>
              <strong>Phone:</strong> +1 5589 55488 55<br>
              <strong>Email:</strong> info@example.com<br>
            </p>
            <div class="social-links mt-3">
              <a href="#" class="twitter"><i class="bx bxl-twitter"></i></a>
              <a href="#" class="facebook"><i class="bx bxl-facebook"></i></a>
              <a href="#" class="instagram"><i class="bx bxl-instagram"></i></a>
              <a href="#" class="google-plus"><i class="bx bxl-skype"></i></a>
              <a href="#" class="linkedin"><i class="bx bxl-linkedin"></i></a>
            </div>
          </div>

          <div class="col-lg-4 col-md-6 footer-links">
           <center> <h4> Weekly Activities</h4></center>
            <ul>
              <li><i class="bx bx-chevron-right"></i>Tuesday: Digging Deep 5:00pm -- 6:00pm</li>
              <li><i class="bx bx-chevron-right"></i>Thurday: Faith Clinic 5:00pm -- 6:00pm</li>
              <li><i class="bx bx-chevron-right"></i>Sunday:First Service 7:30am </li>
              <li><i class="bx bx-chevron-right"></i>Sunday:Second Service 9:15am</li>
              <li><i class="bx bx-chevron-right"></i>Wenesday: Solution Hour 6:00am -- 7:00am</li>
              <li><i class="bx bx-chevron-right"></i>Saturday: Prayer 7:00am -- 8:00am</li>
            </ul>
          </div>

          <div class="col-lg-4 col-md-6 footer-links">
            <h4>Useful Links</h4>
            <ul>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Home</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Units</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Media</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Pastors Desk</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Contact Us</a></li>
            </ul>
          </div>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="copyright">
        &copy; Copyright <strong><span>House Of Mercy</span></strong>. All Rights Reserved
      </div>
      <div class="credits">
        <!-- All the links in the footer should remain intact. -->
        <!-- You can delete the links only if you purchased the pro version. -->
        <!-- Licensing information: https://bootstrapmade.com/license/ -->
        <!-- Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/bootstrap-3-one-page-template-free-shuffle/ -->
        Designed by <a href="">House Of Mercy Media Team</a>
      </div>
    </div>
  </footer>
  <script src="{% static 'assets/vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'assets/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'assets/vendor/jquery.easing/jquery.easing.min.js' %}"></script>
  <script src="{% static 'assets/vendor/php-email-form/validate.js' %}"></script>
  <script src="{% static 'assets/vendor/jquery-sticky/jquery.sticky.js' %}"></script>
  <script src="{% static 'assets/vendor/waypoints/jquery.waypoints.min.js' %}"></script>
  <script src="{% static 'assets/vendor/counterup/counterup.min.js' %}"></script>
  <script src="{% static 'assets/vendor/isotope-layout/isotope.pkgd.min.js' %}"></script>
  <script src="{% static 'assets/vendor/owl.carousel/owl.carousel.min.js' %}"></script>
  <script src="{% static 'assets/vendor/venobox/venobox.min.js' %}"></script>

  <!-- Template Main JS File -->
  <script src="{% static 'assets/js/main.js' %}"></script>
  <script src="{% static 'assets/js/lightbox.min.js' %}"></script>
</body>
</html>

app/templates/inc/slider.html
<!-- {% for slide in wale %}
		<div class="carousel-item active">
            <div class="carousel-background"><img src="{{ slide.thumb.url }}" alt=""></div>
            <div class="carousel-container">
              <div class="carousel-content">
                <h2 class="animate__animated animate__fadeInDown"> <span>{{slide.first }}</span></h2>
                <p class="animate__animated animate__fadeInUp">{{slide.second}}</p>
                <a href="" class="btn-get-started animate__animated animate__fadeInUp scrollto">Get Started</a>
              </div>
            </div>
         </div>
{% endfor %}


 
 -->