app/urls.py
from django.urls import path
from . import views


app_name = 'app'
urlpatterns = [
    path('',views.home, name='home'),
    path('message/',views.message, name='message'),
    path('gallary2/',views.gallary2, name='gallary2'),
    path('gallary/',views.gallary, name='gallary'),
    path('more/',views.pastor_more, name='more'),
    path('videos/',views.videos, name='video'),
    path('audio/',views.audios_video, name='audio'),
    path('audios/',views.audios, name='audio'),
    path('events/',views.events, name='events'),
    path('pastors_unit/',views.pastors_unit, name='pastors_unit'),
    path('contact/',views.contact_us, name='contact_us'),

    #UNITS
    path('choir/',views.choir, name='choir'),
    path('usher/',views.ushers, name='ushers'),
    path('media/',views.media, name='media'),
    path('decoration/',views.decoration, name='decoration'),
    path('sanitation/',views.sanitation, name='sanitation'),
    path('protocol/',views.protocol, name='protocol'),
    path('security_unit/',views.security, name='security'),
    path('sunday_school/',views.sunday, name='sunday_school'),
    path('technical/',views.technical, name='technical'),





    path('<slug>/',views.details, name='detail'),



]

control_panel/urls.py
from django.urls import path

from newsletter.views import control_newsletter, control_newsletter_list


app_name = 'control'
urlpatterns = [
	path('newsletter/', control_newsletter, name='control_newsletter'),
	path('newsletter-list/', control_newsletter_list, name='control_newsletter_list'),
]

mercy/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings 


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('app.urls')),
    path('control/',include('control_panel.urls')),
    path('news/',include('newsletter.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

control_panel/models.py
from django.db import models

# Create your models here.

control_panel/views.py
from django.shortcuts import render

# Create your views here.

app/templates/control_panel/control_newsletter.html
{% extends "inc/control_base.html" %}
{% load static %}

{% block content %}
  <div class="container">
  	<div class="row">
  		<div class="col-md-2">
  			
  		</div>

  		<div class="col-md-8">
		  	<form method="POST">{% csrf_token %}
		      {{ form }} 
		     <center><button class="btn btn-info mt-2 mb-2" type="submit">Send</button></center>
		   </form> 
  		</div>

  		<div class="col-md-2">
  			
  		</div>
  	</div>
  </div>
{% endblock %}

app/templates/control_panel/control_newsletter_list.html
{% extends "inc/control_base.html" %}
{% load static %}

{% block content %}
	<div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
		<div class="row mt-3">
			<div class="col-sm-10">
				<h1 class="page-header">All NewsLetters</h1>
			</div>
			<div class="col-sm-2">
				<a href="{% url 'control:control_newsletter' %}"><button type="button" class="btn btn-success">New NewsLetter</button></a>				
			</div>
		</div> 
		<div class="table-responsive table-hover">
			<table class="table">
				<thead>
					<th>Subject</th>
					<th>Status</th>
					<th>Created</th>
					<th>Update</th>
					<th>Edit</th>
					<th>Delete</th>
				</thead>
				<tbody>
					{% for item in items %}
						<tr>
							<td>{{item.subject}}</td>
							<td>{{item.status}}</td>
							<td>{{item.created}}</td>
							<td>{{item.updated}}</td>
							<td><a href="#">Edit</a></td>
							<td><a href="#">Delete</a></td>
						</tr>
					{% endfor %}
				</tbody>
			</table>
		</div>
		
	</div>
{% endblock %}