app/urls.py
from django.urls import path
from . import views


app_name = 'app'
urlpatterns = [
    path('',views.home, name='home'),
    path('message/',views.message, name='message'),
    path('gallary2/',views.gallary2, name='gallary2'),
    path('gallary/',views.gallary, name='gallary'),
    path('more/',views.pastor_more, name='more'),
    path('videos/',views.videos, name='video'),
    path('audio/',views.audios_video, name='audio'),
    path('audios/',views.audios, name='audio'),
    path('events/',views.events, name='events'),
    path('pastors_unit/',views.pastors_unit, name='pastors_unit'),
    path('contact/',views.contact_us, name='contact_us'),

    #UNITS
    path('choir/',views.choir, name='choir'),
    path('usher/',views.ushers, name='ushers'),
    path('media/',views.media, name='media'),
    path('decoration/',views.decoration, name='decoration'),
    path('sanitation/',views.sanitation, name='sanitation'),
    path('protocol/',views.protocol, name='protocol'),
    path('security_unit/',views.security, name='security'),
    path('sunday_school/',views.sunday, name='sunday_school'),
    path('technical/',views.technical, name='technical'),





    path('<slug>/',views.details, name='detail'),



]

mercy/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings 


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('app.urls')),
    path('control/',include('control_panel.urls')),
    path('news/',include('newsletter.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/templates/pages/audio.html
{% extends 'inc/base.html' %}
{% load embed_video_tags %}

{% load static %}
{% block content %}

	<div class="container">
	<div class="row">
		<div class="col-md-3" >	
		</div>

		<div class="col-md-6" >
			<center><h1>Our Sunday Sermon Audios</h1></center>
		</div>


		<div class="col-md-3" >	
		</div>
	</div>
	<div class="row">
		{% for i in wale %}

		<div class="col-lg-4 col-md-8 d-flex align-items-stretch mb-5 mt-2 mb-lg-2">
   				 {% video i.video 'small' %}

		</div>
	    {% endfor %}

	</div>
</div>
{% endblock content %}

app/templates/pages/contact_form.html
{% extends 'inc/base.html' %}
{% load static %}
{% block content %}



	<div class="row">
		<div class="col-md-3">
			
		</div>

		<div class="col-md-6">
			<form class="form-horizontal" role="form" method="POST">
				 {% csrf_token %}

			  <div class="form-group">
			    <label class="control-label col-sm-2" for="email">Name:</label>
			    <div class="col-sm-10">
                  {{ form.name }}
			    </div>
			  </div>
			  
			  <div class="form-group">
				   <label class="control-label col-sm-2" for="pwd">Subject:</label>
				    <div class="col-sm-10">
                  {{ form.subject }}
				    </div>
			  </div>

			  <div class="form-group">
				   <label class="control-label col-sm-2" for="pwd">Request:</label>
				    <div class="col-sm-10">
                  {{ form.message }}
				    </div>
			  </div>
			  {% if messages %}
				{% for message in massages %}
					<div class="alert alert-success"  role="alert">
						{{ message }}
					</div>
				{% endfor %}
			 {% endif %}

			  <div class="form-group">
			    <div class="col-sm-offset-2 col-sm-10">
			      <button type="submit" class="btn btn-info">Submit</button>
			    </div>
			  </div>
			</form>
		</div>

		<div class="col-md-3">
			
		</div>
	</div>
{% endblock content %}

app/templates/pages/event_details.html
{% extends 'inc/base.html' %}
{% load static %}

{% block content %}
<div class="container">
	<div class="row">
		<div class="card m-auto">
			<div class="card-body my-2">
				<h1 class="card-title">{{ message.name }}</h1>
				<p class="card-text">{{ message.description }}</p>
				<p class="card-text">{{ message.date }}</p>
			</div>
		</div>
	</div>
</div>
{% endblock %}

app/templates/pages/events.html
{% extends 'inc/base.html' %}
{% load static %}

{% block content %}
<section class="more-services section-bg">
    <div class="container">

        <div class="section-title">
          <h2>Upcoming Events</h2>
        </div>

        <div class="row">
        {% for events in events %}

        <div class="col-lg-4 col-md-6 d-flex align-items-stretch mb-5 mb-lg-0">
            <div class="card">
             <img src="{{ events.thumb.url }}" class="card-img-top" alt="...">
              <div class="card-body">
                <h5 class="card-title"><a href="{{ events.thumb.url }}" data-lightbox="gallary" data-title="{{ events.name }}">{{ events.name }}</a></h5>
                <p class="card-text">{{ events.snippet }}</p>
         </div>
            </div>
         </div>

        {% endfor %}

      </div>
      <a href="https://paystack.com/pay/153cdsf4vr" class="btn btn-success">Pay</a>
    </div>
</section>
{% endblock %}

app/templates/pages/gallary.html
{% extends 'inc/base.html' %}
{% load static %}
{% block content %}

<section id="team" class="team">
	<div class="container">
		<div class="row">
		{% for gallary in wale %}

			<div class="col-lg-3 col-md-6 d-flex align-items-stretch mb-5 mb-lg-0 " data-wow-delay="0.1s">
				<div class="member">
	             <img src="{{ gallary.thumb.url }}" class="img-fluid" alt="" >
	              <div class="member-info">
	                <div class="member-info-content">
	                  <a href="{{ gallary.thumb.url }}" data-lightbox="gallary" data-title="{{ gallary.description }}"><h4>{{ gallary.description }}</h4></a>
	                </div>
	                
	              </div>
	            </div>
			</div>
		{% endfor %}
		</div>
	</div>
</section>
{% endblock content %}

app/templates/pages/gallary2.html
{% extends 'inc/base.html' %}
{% load static %}
{% block content %}
<div class="container">
		<div class="row">
			{% for gallary in wale %}

			<div class="col-lg-3 col-md-6 d-flex align-items-stretch mb-5  mb-lg-0 " data-wow-delay="0.1s">
					<div class="member">
		            <a href="{{ gallary.thumb.url }}" data-lightbox="gallary" data-title="{{ gallary.description }}"> <img src="{{ gallary.thumb.url }}" class="img-fluid" alt="" ></a>
		              <div class="member-info">
		                <div class="member-info-content">
		                  <span></span>
		                </div>
		                
		              </div>
		            </div>
			</div>
			{% endfor %}
		</div>
</div>
{% endblock content %}

app/templates/pages/home.html
{% extends 'inc/base.html' %}
{% load static %}
{% block content %}
<section id="hero">
    <div class="hero-container">
      <div id="heroCarousel" class="carousel slide carousel-fade" data-ride="carousel">

        <ol class="carousel-indicators" id="hero-carousel-indicators"></ol>

        <div class="carousel-inner" role="listbox">

          <!-- Slide 1 -->
          <div class="carousel-item active">
            <div class="carousel-background"><img src="{% static 'assets/img/slide/DSC_7027 copy.jpg' %}" alt=""></div>
            <div class="carousel-container">
              <div class="carousel-content">
                <h2 class="animate__animated animate__fadeInDown">Welcome to <span>RCCG House Of Mercy <br>Official Website</span></h2>
                <p class="animate__animated animate__fadeInUp">Praise the Lord for the Lord is good: sing praises unto his name; for it is Pleasant</p>
              </div>
            </div>
          </div>

          <!-- Slide 2 -->
          <div class="carousel-item">
            <div class="carousel-background"><img src="{% static 'assets/img/slide/DSC_7053_filtered copy.jpg' %}" alt=""></div>
            <div class="carousel-container">
              <div class="carousel-content">
                <h2 class="animate__animated animate__fadeInDown">Those that Wait On the Lord He Shall Renew Their Strength</h2>
                <p class="animate__animated animate__fadeInUp">Then they cried unto the Lord in their trouble, and he delivered them out of distresses And he lead them forth by the right way, that they might go to the city of habitation:<br> Psalm 107 vs 6-7</p>
              </div>
            </div>
          </div>

          <!-- Slide 3 -->
          <div class="carousel-item">
            <div class="carousel-background"><img src="{% static 'assets/img/slide/DSC_7044 copy.jpg' %}" alt=""></div>
            <div class="carousel-container">
              <div class="carousel-content">
                <h2 class="animate__animated animate__fadeInDown">Praise the Lord for the Lord is good: sing praises unto his name; for it is Pleasant</h2>
                <p class="animate__animated animate__fadeInUp">Serve the Lord with gladness, all who are his people, Be thankful unto Him and bless His name</p>
                DSC_7058 copy.jpg
              </div>
            </div>
          </div>

          <!--Slide 4 -->
          <div class="carousel-item">
            <div class="carousel-background"><img src="{% static 'assets/img/slide/DSC_7058 copy.jpg' %}" alt=""></div>
            <div class="carousel-container">
              <div class="carousel-content">
                <h2 class="animate__animated animate__fadeInDown">Come On To Me All You that are werry and heavy leaden and I shall give you rest</h2>
                <p class="animate__animated animate__fadeInUp">When the Lord turn the captivity of zion, we were like them that dream, then our mouth was filled with laughter, and our tongue with singing: then it was said amoung the heathen, the Lord has done Great thing</p>
                
              </div>
            </div>
          </div>

          <div class="carousel-item">
            <div class="carousel-background"><img src="{% static 'assets/img/slide/DSC_7055 copy.jpg' %}" alt=""></div>
            <div class="carousel-container">
              <div class="carousel-content">
                <h2 class="animate__animated animate__fadeInDown">Call upon me and i will show you great and mighty things</h2>
                <p class="animate__animated animate__fadeInUp">If you're willing and obedient ye shall eat the good of the land but if ye refuse and rebel, ye shall be devoured with the sword, for the mouth of the Lord has spoken it!</p>
                
              </div>
            </div>
          </div>
        </div>

        <a class="carousel-control-prev" href="#heroCarousel" role="button" data-slide="prev">
          <span class="carousel-control-prev-icon icofont-thin-double-left" aria-hidden="true"></span>
          <span class="sr-only">Previous</span>
        </a>

        <a class="carousel-control-next" href="#heroCarousel" role="button" data-slide="next">
          <span class="carousel-control-next-icon icofont-thin-double-right" aria-hidden="true"></span>
          <span class="sr-only">Next</span>
        </a>

      </div>
    </div>
</section>
	

 <section id="about" class="about">
      <div class="container">

        <div class="section-title">
          <h2>From The Pastor</h2>
          
        </div>

       <div class="row">
          <div class="col-md-6">
            <img src="{% static 'assets/img/IMG_20200815_133418_753.jpg' %}" class="img-fluid" alt="">
          </div>
        <div class="col-lg-6 pt-4 pt-lg-0 content">
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
            tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
            quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
            consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
            cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
            proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
            tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
            quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
            consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
            cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat nonquis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
            consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
            cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat noncillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
            </p>
        
         </div>
        </div>

      </div>
 </section><!-- End About Us Section -->

<section class="cta">
      <div class="container">

        <div class="text-center">
          <h3></h3>
          <p> </p>
          <a class="cta-btn" href="#">Call To Action</a>
        </div>

      </div>
</section>

<section class="more-services section-bg">
      <div class="container">
      	<div class="section-title">
          <h2>From The Pastor Desks</h2>
          
        </div>
<div class="row">
				 {% for message in wale %}

				<div class="col-lg-3 col-md-6 d-flex align-items-stretch mb-5 mb-lg-0 ">

		            <div class="card">
		              <div class="card-body">
		                <h5 class="card-title"><a href="">{{ message.subject }} </a></h5>
		                <p class="card-text"> {{ message.snippet }}</p>
                    <p class="card-text"><strong>{{ message.date }}</strong></p>

                 <a href="{% url 'app:detail' message.slug %}" class="btn">Explore more</a>
		              </div>
		             </div>
				</div>

			{% endfor %}

   <!-- <a href="{% url 'app:more'%}" class="btn mt-2" style="margin-left: 500px">View More</a> -->

</div>
</section>

{% endblock content %}

app/templates/pages/messages.html
{% extends 'inc/base.html' %}
{% load static %}
{% block content %}
<div class="container">
	<div class="row">
		<div class="col-md-3">
			
		</div>

		<div class="col-md-6 mt-4 mb-4">
			<center><h2>Thank You For Sending you prayer request be rest assured Daddy will be praying for you and remember Jesus Loves you </h2></center>
		</div>

		<div class="col-md-3">
			
		</div>
	</div>
</div>
			
{% endblock content %}

app/templates/pages/pastor_detail.html
{% extends 'inc/base.html' %}
{% load static %}

{% block content %}
<div class="container">
	<div class="row">
		<div class="card m-auto">
			<div class="card-body my-2">
				<h1 class="card-title">{{ message.subject }}</h1>
				<p class="card-text">{{ message.message }}</p>
				<p class="card-text">{{ message.date }}</p>
			</div>
		</div>
	</div>
</div>
{% endblock %}

app/templates/pages/pastor_more.html
{% extends 'inc/base.html' %}
{% load static %}

{% block content %}
<section class="more-services section-bg">
 <div class="container">
      <div class="section-title">
          <h2>More From The Pastor Desks</h2>
          
       </div>
		<div class="row">
						{% for message in wale %}

				<div class="col-lg-3 col-md-6 d-flex align-items-stretch mb-5 mb-lg-0 mt-3 ">

				            <div class="card">
				              <div class="card-body">
				                <h5 class="card-title"><a href="">{{ message.subject }}</a></h5>
				                <p class="card-text">{{ message.snippet }}</p>
				                <p class="card-text"><strong>{{ message.date }}</strong></p>
				                <a href="{% url 'app:detail' message.slug %}" class="btn">Explore more</a>
				             </div>
				 </div>
		</div>
						{% endfor %}
						<hr>

</div>
</section>
{% endblock %}

app/templates/pages/pastors_unit.html
{% extends 'inc/base.html' %}
{% load static %}

{% block content %}

<section id="team" class="team">
  <div class="container">

	    <div class="section-title">
	      <h2>Our Pastors Unit</h2>
	      <p>Magnam dolores commodi suscipit. Necessitatibus eius consequatur ex aliquid fuga eum quidem. Sit sint consectetur velit. Quisquam quos quisquam cupiditate. Et nemo qui impedit suscipit alias ea. Quia fugiat sit in iste officiis commodi quidem hic quas.</p>
	    </div>
		<div class="row">
		{% for pastor in wale %}

			<div class="col-xl-3 col-lg-4 col-md-6" data-wow-delay="0.1s">
	            <div class="member">
	              <img src="{{ pastor.thumb.url }}" class="img-fluid" alt="">
	              <div class="member-info">
	                <div class="member-info-content">
	                  <h4>{{ pastor.name }}</h4>
	                </div>
	                <div class="social">
	                  <a href="{{pastor.twitter}}"><i class="icofont-twitter"></i></a>
	                  <a href="{{pastor.fbook}}"><i class="icofont-facebook"></i></a>
	                </div>
	              </div>
	            </div>
	        </div>
	          {% endfor %}

	        </div>
	</div>
</section>
{% endblock %}

app/templates/pages/videos.html
{% extends 'inc/base.html' %}
{% load embed_video_tags %}

{% load static %}
{% block content %}

	<div class="container">
	<div class="row">
		<div class="col-md-3" >	
		</div>

		<div class="col-md-6" >
			<center><h1>Our Sunday Sermon Videos</h1></center>
		</div>


		<div class="col-md-3" >	
		</div>
	</div>
	<div class="row">
		{% for i in wale %}

		<div class="col-lg-4 col-md-8 d-flex align-items-stretch mb-5 mt-2 mb-lg-2">
   				 {% video i.video 'small' %}

		</div>
	    {% endfor %}

	</div>
</div>
{% endblock content %}